[tool.usort]
first_party_detection = false

[build-system]
requires = ["setuptools", "wheel", "torch", "ninja"]

build-backend = "setuptools.build_meta:__legacy__"

first_party_detection = false

target-version = ["py38"]

excludes = [
    "gallery",
    "tutorials",
]