[tool.usort]
first_party_detection = false

[build-system]
requires = ["setuptools", "wheel", "torch", "ninja"]

first_party_detection = false

target-version = ["py38"]

excludes = [
    "gallery",
    "tutorials",
]

[tool.pytest.ini_options]
addopts = "-ra --tb=native"
testpaths = ["test"]
xfail_strict = true
pythonpath = "torchrl"